on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Java Library
        shell: bash
        run: |
          javac ./test/src/HelloWorld.java -d ./build

      - name: Build Java Jar
        shell: bash
        run: |
          jar cmf ./test/src/HelloWorld.mf ./test/src/build/HelloWorld.jar ./test/src/build/HelloWorld.class ./test/src/HelloWorld.java

      - name: Sign Files
        uses: ./
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ./test/src/build/HelloWorld.jar
          output_path: ./artifacts
          malware_block: false
          environment_name: PROD
          override: false
          clean_logs: false

  sign-override:
    runs-on: ubuntu-latest
    name: Sign with override options
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Java Library
        shell: bash
        run: |
          javac ./test/src/HelloWorld.java -d ./build

      - name: Build Java Jar
        shell: bash
        run: |
          jar cmf ./test/src/HelloWorld.mf ./test/src/build/HelloWorld.jar ./test/src/build/HelloWorld.class ./test/src/HelloWorld.java

      - name: Sign Files
        uses: ./
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ./test/src/build/HelloWorld.jar
          output_path: ./artifacts
          malware_block: false
          environment_name: PROD
          override: true
          clean_logs: true

  sign-external:
    runs-on: ubuntu-latest
    name: Sign with External Repo
    steps:
      - uses: ./
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ./test/sign/Depths1.exe
          output_path: ./artifacts
          malware_block: false
          environment_name: PROD

  batch-sign:
    runs-on: ubuntu-latest
    name: Run Batch Signing
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          dir_path: ./test/sign
          output_path: ./test/signed
          environment_name: PROD
